### ISSUE TITLE
bytes protobuf type gives unhelpful segfault

### ISSUE THREAD

**Issue by drewwells** [infobloxopen/protoc-gen-gorm#218]
```
message Request {
  bytes payload = 1;
}
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x7149d1]

goroutine 1 [running]:
github.com/infobloxopen/protoc-gen-gorm/plugin.(*ORMBuilder).followsCreateConventions(0xc000814540, 0xc0006b8fc0, 0xc0006b9200, {0x7bb7bb, 0x6})
        /go/pkg/mod/github.com/infobloxopen/protoc-gen-gorm@v1.0.0/plugin/plugin.go:2644 +0x131
github.com/infobloxopen/protoc-gen-gorm/plugin.(*ORMBuilder).parseServices(0xc000814540, 0xc0008ec600)
        /go/pkg/mod/github.com/infobloxopen/protoc-gen-gorm@v1.0.0/plugin/plugin.go:2596 +0x64c
github.com/infobloxopen/protoc-gen-gorm/plugin.(*ORMBuilder).Generate(0xc000814540)
        /go/pkg/mod/github.com/infobloxopen/protoc-gen-gorm@v1.0.0/plugin/plugin.go:280 +0x251
main.main()
        /go/pkg/mod/github.com/infobloxopen/protoc-gen-gorm@v1.0.0/main.go:33 +0xb0
--gorm_out: protoc-gen-gorm: Plugin failed with status code 2.
```

**Comment by luca3rd** [comment]
I'm also running into this issue on `v1.1.0`. Is there any fix for this?

**Comment by mewis** [comment]
I am also having this issue aswell.
seems to be related to having a rpc named `UpdateXYZ`

**Comment by mewis** [comment]
This also happens even if the service does not have 
`option (gorm.server).autogen = true`
